global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'banking-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'api-gateway:8080'
        - 'auth-service:8081'
        - 'profile-service:8082'
        - 'account-service:8083'
        - 'transaction-service:8084'
        - 'notification-service:8085'
